version: '3'

services:
  api:
    build:
      context: ./api_server
      dockerfile: Dockerfile
    ports:
      - "${API_PORT:-5000}:5000"
    volumes:
      - ./data:/app/data
    environment:
      - FLASK_ENV=${FLASK_ENV:-production}
      - FLASK_APP=src/main.py
      - SECRET_KEY=${SECRET_KEY:-default-secret-key}
      - CORS_ORIGINS=${CORS_ORIGINS:-*}
    restart: unless-stopped

  web:
    build:
      context: ./web_ui
      dockerfile: Dockerfile
    ports:
      - "${WEB_PORT:-80}:80"
    environment:
      - VITE_API_URL=${API_URL:-http://localhost:5000}
    depends_on:
      - api
    restart: unless-stopped

